apiVersion: v1
kind: Service
metadata:
  name: service-z2
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30080
