apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}-{{ .Values.version.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}-{{ .Values.version.name }}
  ports:
    - protocol: {{ .Values.backend.serviceProtocol }}
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.targetPort }}
