apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-{{ .Values.version.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}-{{ .Values.version.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}-{{ .Values.version.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.containerName }}
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
