apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}-{{ .Values.version.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}-{{ .Values.version.name }}
  ports:
    - protocol: {{ .Values.frontend.serviceProtocol }}
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.targetPort }}
