apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/data/date.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt/data
      - name: multitool
        image: praqma/network-multitool
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt/data
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc
