apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: custom
      protocol: TCP
      port: 81
      targetPort: 1180
