apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      initContainers:
      - name: init-busybox
        image: busybox
        command: ['sh', '-c', 'until nslookup wait-service.default.svc.cluster.local; do echo waiting for service; sleep 2; done;']
      containers:
      - name: nginx
        image: nginx:1.14.2
